### ISSUE TITLE
Disable Account Confirmation

### ISSUE THREAD

**Issue by Solidary** [Zizaco/confide#272]
Hi,

Please how to disable the account confirmation through email ?

Thanks.

**Comment by MatKershaw** [comment]
I have the same issue as Thatdoorsajar after updating.

It's always returning false from the confirmUser function at line 135 in the EloquentRepository.php file, because user->save on line 137 is always failing.

This took me hours to track down and in the meantime users were unable to sign up.

But I see the issue is closed.
